/**
 * NoteTaker API
 * API for my React practice project
 *
 * The version of the OpenAPI document: v1
 * Contact: canthavemy@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NoteTakerApi);
  }
}(this, function(expect, NoteTakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NoteTakerApi.NotebookApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NotebookApi', function() {
    describe('apiNotebookGet', function() {
      it('should call apiNotebookGet successfully', function(done) {
        //uncomment below and update the code to test apiNotebookGet
        //instance.apiNotebookGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiNotebookIdDelete', function() {
      it('should call apiNotebookIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiNotebookIdDelete
        //instance.apiNotebookIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiNotebookIdGet', function() {
      it('should call apiNotebookIdGet successfully', function(done) {
        //uncomment below and update the code to test apiNotebookIdGet
        //instance.apiNotebookIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiNotebookPost', function() {
      it('should call apiNotebookPost successfully', function(done) {
        //uncomment below and update the code to test apiNotebookPost
        //instance.apiNotebookPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
