/**
 * NoteTaker API
 * API for my React practice project
 *
 * The version of the OpenAPI document: v1
 * Contact: canthavemy@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NoteTakerApi);
  }
}(this, function(expect, NoteTakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NoteTakerApi.NoteApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NoteApi', function() {
    describe('apiNoteGet', function() {
      it('should call apiNoteGet successfully', function(done) {
        //uncomment below and update the code to test apiNoteGet
        //instance.apiNoteGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiNoteIdDelete', function() {
      it('should call apiNoteIdDelete successfully', function(done) {
        //uncomment below and update the code to test apiNoteIdDelete
        //instance.apiNoteIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiNoteIdGet', function() {
      it('should call apiNoteIdGet successfully', function(done) {
        //uncomment below and update the code to test apiNoteIdGet
        //instance.apiNoteIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiNotePost', function() {
      it('should call apiNotePost successfully', function(done) {
        //uncomment below and update the code to test apiNotePost
        //instance.apiNotePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
