/**
 * NoteTaker API
 * API for my React practice project
 *
 * The version of the OpenAPI document: v1
 * Contact: canthavemy@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NoteTakerApi);
  }
}(this, function(expect, NoteTakerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NoteTakerApi.Note();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Note', function() {
    it('should create an instance of Note', function() {
      // uncomment below and update the code to test Note
      //var instance = new NoteTakerApi.Note();
      //expect(instance).to.be.a(NoteTakerApi.Note);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new NoteTakerApi.Note();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new NoteTakerApi.Note();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new NoteTakerApi.Note();
      //expect(instance).to.be();
    });

    it('should have the property notebookId (base name: "notebookId")', function() {
      // uncomment below and update the code to test the property notebookId
      //var instance = new NoteTakerApi.Note();
      //expect(instance).to.be();
    });

    it('should have the property notebook (base name: "notebook")', function() {
      // uncomment below and update the code to test the property notebook
      //var instance = new NoteTakerApi.Note();
      //expect(instance).to.be();
    });

  });

}));
