/**
 * NoteTaker API
 * API for my React practice project
 *
 * The version of the OpenAPI document: v1
 * Contact: canthavemy@email.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Note from './model/Note';
import Notebook from './model/Notebook';
import NotebookColor from './model/NotebookColor';
import User from './model/User';
import NoteApi from './api/NoteApi';
import NotebookApi from './api/NotebookApi';
import UserApi from './api/UserApi';


/**
* API for my React practice project.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NoteTakerApi = require('index'); // See note below*.
* var xxxSvc = new NoteTakerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NoteTakerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NoteTakerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NoteTakerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Note model constructor.
     * @property {module:model/Note}
     */
    Note,

    /**
     * The Notebook model constructor.
     * @property {module:model/Notebook}
     */
    Notebook,

    /**
     * The NotebookColor model constructor.
     * @property {module:model/NotebookColor}
     */
    NotebookColor,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The NoteApi service constructor.
    * @property {module:api/NoteApi}
    */
    NoteApi,

    /**
    * The NotebookApi service constructor.
    * @property {module:api/NotebookApi}
    */
    NotebookApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
